# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Webpad',
        ),
    ]
