# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpad', '0002_auto_20180317_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpad',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
