# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpad', '0003_webpad_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpad',
            name='published_date',
        ),
    ]
